variables:
    NUGET_PROJECT_DIR: src/Snip

release:
    stage: deploy
    rules:
        - if: $CI_COMMIT_BRANCH == "production"
    image: mcr.microsoft.com/dotnet/sdk:5.0
    variables:
        PUBLISH_SOURCE_URL: https://api.nuget.org/v3/index.json
        API_KEY: $NUGET_API_KEY
    script:
        - |
          dotnet build --configuration Release "$NUGET_PROJECT_DIR"
          dotnet pack --configuration Release "$NUGET_PROJECT_DIR" --no-build --output .ci/package
        - dotnet nuget push .ci/package/*.nupkg --source $PUBLISH_SOURCE_URL --api-key $API_KEY --skip-duplicate
    artifacts:
        paths:
        - .ci/package/*
    environment:
        name: production
        url: https://www.nuget.org/packages/Andtech.Snip
