name: Release package

env:
  NUGET_SOURCE_URL: https://gitlab.com/api/v4/projects/29250253/packages/nuget
  NUGET_PROJECT_DIR: src/Snip/Snip.csproj

on:
  create:
    tags:
      - v*
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: "Build project"
        run: |
          dotnet build --configuration Release "${{env.NUGET_PROJECT_DIR}}"
          dotnet pack --configuration Release "${{env.NUGET_PROJECT_DIR}}" --no-build --output .
      - name: "Deploy to GitLab"
        run: |
          dotnet nuget add source "${{env.NUGET_SOURCE_URL}}/index.json" --name gitlab --username "${{secrets.GITLAB_ACCESS_TOKEN_OWNER}}" --password "${{secrets.GITLAB_ACCESS_TOKEN}}" --store-password-in-clear-text
          dotnet nuget push *.nupkg --source gitlab --api-key "${{secrets.GITLAB_ACCESS_TOKEN}}" --skip-duplicate
